# The purpose of this script is to read several files, that were generated by a test using
# a Smartphone's movement sensors, and merget them in 1 tidy file to be used for further anaylsis. 


# Read in the "train" file set and merge them into one file
        # Read in the xtrain file that contains the actual data generated by the sensors
        xtrain <- read.table("./train/X_train.txt", header=FALSE,sep="")
        # Read in the column head file which are called features        
        feature_headers <- read.table("./features.txt", header=FALSE,sep="")
        colnames(feature_headers) <- c("ID","Header")
        # Remove some unwanted characters from the header names
        feature_headers$Header <-gsub("\\()","",feature_headers$Header)
        feature_headers$Header <-gsub("\\,","-",feature_headers$Header)
        # Set the column headers
        colnames(xtrain) <- feature_headers[,2]
        
        # Read in the Activity keys for the training set.  In this file, there
        # is a row for each observation that specifies what activity was taking place 
        # for the observation
        ytrain <- read.table("./train/Y_train.txt", header=FALSE,sep="")
        # Create a new Activity variable to give to give a discriptive activity name for each observation
        ytrain$Activity <- factor(ytrain$V1,labels=c("WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIRS","SITTING","STANDING","LAYING"))
        
        # Read in the subject keys for the training set.  In this file, there contains 
        #a row for each observation that specifies the subject that was the performing 
        # the operation.
        subjectTrain <- read.table("./train/subject_train.txt", header=FALSE,sep="")
        colnames(subjectTrain) <- c("subjectID")
        
        # Create the final tidy file by first merging the activity file with the xtrain file to add the 
        # actvity discriptive field to the training file
        train <- cbind2(ytrain$Activity,xtrain)
        # Merge the subject file to the new train file to bind the subject to the data.
        train <- cbind2(subjectTrain,train)
        
        # Rename the first 2 variables in train file
        colnames(train)[1] <- "SubjectID"
        colnames(train)[2] <- "ActivityName"

        head(train)
# Read in the "test" file set and merge them into one file
        # Read in the xtrain file that contains the actual data generated by the sensors
        xtest <- read.table("./test/X_test.txt", header=FALSE,sep="")

        # Set the column headers
        colnames(xtest) <- feature_headers[,2]
        
        # Read in the Activity keys for the training set.  In this file, there
        # is a row for each observation that specifies what activity was taking place 
        # for the observation
        ytest <- read.table("./test/Y_test.txt", header=FALSE,sep="")
        # Create a new Activity variable to give to give a discriptive activity name for each observation
        ytest$Activity <- factor(ytest$V1,labels=c("WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIRS","SITTING","STANDING","LAYING"))
        
        # Read in the subject keys for the training set.  In this file, there contains 
        #a row for each observation that specifies the subject that was the performing 
        # the operation.
        subjectTest <- read.table("./test/subject_test.txt", header=FALSE,sep="")
        colnames(subjectTest) <- c("subjectID")
        
        # Create the final tidy file by first merging the activity file with the xtrain file to add the 
        # actvity discriptive field to the training file
        test <- cbind2(ytest$Activity,xtest)
        # Merge the subject file to the new train file to bind the subject to the data.
        test <- cbind2(subjectTest,test)
        
        # Rename the first 2 variables in train file
        colnames(test)[1] <- "SubjectID"
        colnames(test)[2] <- "ActivityName"
        
        head(test)